import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";
import "@/styles/globals.css";
import Provider from "@/components/Provider";

export const metadata: Metadata = {
  title: "BollyFoodMarket",
  description: "Generated by create ElHombreDeLaNoche",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className={"bg-[#fbf4e7]"}>
          <section className="flex flex-col min-h-screen">
            <Header />
            <main className="m-5">
              <section>{children}</section>
            </main>
            <Footer />
          </section>
        </body>
      </Provider>
    </html>
  );
}
