import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "BollyFoodMarket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"bg-[#fbf4e7]"}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <section className="p-4">
            <div className="p-4 mx-auto">{children}</div>
          </section>
          <Footer />
        </div>
      </body>
    </html>
  );
}
